notifications:
  email: false

sudo: required

language: python

services:
- docker

# command to install dependencies
#install: pip install tox-travis
install: pip install tox

#script: make test

script:
- tox
