notifications:
  email: false

sudo: required

language: python

services:
- docker

before_install:
- sudo curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
- sudo chmod +x /usr/local/bin/docker-machine
